version: "3.8"

services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    depends_on:
      - db
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    # entrypoint: sh -c "sleep 30 && php /var/www/artisan migrate"
    # entrypoint: sh -c "sleep 30 && php artisan migrate --seed"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret